### ISSUE TITLE
Typo in peer depedency

### ISSUE THREAD

**Issue by HmFlashy** [yakovlev-alexey/nestjs-amplitude#1]
Hello,
I was trying to add our project as a dependency of my project but there is a problem in the package.json
https://github.com/yakovlev-alexey/nestjs-amplitude/blob/9eca6e6e515cec719ce8fc8e9dfbb631c769ac67/package.json#L35
@apmlitude/node is written instead of @amplitude/node

Thanks

**Comment by yakovlev-alexey** [comment]
Well, that's embarrassing! Fixed the issue in #2 and the package should work properly in version 1.0.3
